version: '3'

services:
  am:
    image: ${AM_IMAGE_NAME}:latest
    container_name: ${AM_IMAGE_NAME}
    stdin_open: true
    tty: true
    build:
      context: am
      args:
        - AM_HOST=${AM_HOST}
        - AM_USERID=${AM_USERID}
        - AM_PASSWORD=${AM_PASSWORD}
        - TOMCAT_VERSION=${OPENAM_TOMCAT_VERSION}
        - OPENAM_VERSION=${OPENAM_VERSION}
        - SSOADM_VERSION=${SSOADM_VERSION}
      
      extra_hosts:
        - "am.myforgerock.com:127.0.0.1"
    environment:
      - CATALINA_OPTS=-Dcom.iplanet.services.debug.level=message
      - JAVA_OPTS=-server -Xms2048m -Xmx2048m -XX:MetaspaceSize=256m -XX:MaxMetaspaceSize=256m -XX:NewRatio=2 -XX:SurvivorRatio=5 -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -Xlog:gc:/opt/openam/tomcat/logcc/logcc -Dorg.apache.tomcat.util.buf.UDecoder.ALLOW_ENCODED_SLASH=true -Djava.util.logging.config.file=/opt/openam/tomcat/conf/logging.properties -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager -Djdk.tls.ephemeralDHKeySize=2048 -Djava.protocol.handler.pkgs=org.apache.catalina.webresources -Dorg.apache.catalina.security.SecurityListener.UMASK=0027 -Dcom.sun.security.enableCRLDP=true -Dorg.apache.xml.security.ignoreLineBreaks=true -Dcatalina.base=/opt/openam/tomcat -Dcatalina.home=/opt/openam/tomcat -Djava.io.tmpdir=/opt/openam/tomcat/temp -Djavax.net.ssl.trustStore=/opt/openam/tomcat/conf/certs/tomcat_keystore.pfx -Djavax.net.ssl.trustStoreType=PKCS12 -Djavax.net.ssl.trustStorePassword=changeit      
    ports:
      - "8080:8080"
      - "8443:8443"
      - "50389:50389"
    hostname: am
    domainname: myforgerock.com
    extra_hosts:
      - "login.myforgerock.com:172.21.0.3"
      - "am.myforgerock.com:172.21.0.2"
      - "idm-devlocal.myforgerock.com:172.21.0.4"
    networks:
      forgenet:
        ipv4_address: 172.21.0.2

  ig:
    image: ig:latest
    container_name: ig
    stdin_open: true
    tty: true
    build:
      context: ig
      args:
        - AM_HOST=${AM_HOST}
        - IG_HOST=${IG_HOST}
        - IG_VERSION=${IG_VERSION}
        - IG_AGENT_PASSWORD=${IG_AGENT_PASSWORD}
        - TOMCAT_VERSION=${IG_TOMCAT_VERSION}
        - OPENAM_TOMCAT_AGENT_VERSION=${OPENAM_TOMCAT_AGENT_VERSION}
        - OPENAM_TOMCAT_AGENT_PASSWORD=${OPENAM_TOMCAT_AGENT_PASSWORD}
    environment:
      - JAVA_OPTS=-server -Xmx756m -Djavax.net.ssl.trustStore=/opt/web/tomcat/conf/certs/tomcat_keystore.pfx -Djavax.net.ssl.trustStorePassword=password -Dorg.forgerock.http.TrustTransactionHeader=true
    ports:
      - "80:8081"
      - "443:8444"
    hostname: login-devlocal
    domainname: myforgerock.com
    extra_hosts:
      - "login.myforgerock.com:172.21.0.3"
      - "am.myforgerock.com:172.21.0.2"
      - "idm-devlocal.myforgerock.com:172.21.0.4"
    networks:
      forgenet:
        ipv4_address: 172.21.0.3

networks:
  forgenet:
    ipam:
      config:
        - subnet: 172.21.0.0/24
